import ReactMarkdown from "react-markdown";
import styles from "./LegalPage.module.css";

const POLICY = `# Privacy Policy

**Last updated:** June 2, 2026

MacAnswers is an independent student-built tool that helps McMaster University students find answers to common questions about university life. This page explains what information we collect, what we do with it, and what your options are.

MacAnswers is **not** an official McMaster University service. It is an independent project developed by a McMaster student and is not endorsed by, affiliated with, or operated by McMaster University. All information returned by MacAnswers is drawn from publicly available McMaster web pages and should always be verified against official McMaster sources for anything time-sensitive or consequential.

## Who this policy applies to

This policy applies to anyone who uses MacAnswers at macanswers.ca.

## What we collect

MacAnswers is designed to collect as little personal information as possible. What we collect depends on how you use the site.

### If you only ask questions

If you use the search feature without signing in, **we do not collect any personal information that identifies you**. We process your questions in real time to generate answers and do not store the question, the answer, or anything connecting you to either.

We may, in the future, begin storing anonymized questions (with no identifying information attached) to help us improve answer quality. If we begin doing this, we will update this policy and post a notice on the site before any logging starts.

For technical reasons, every web request includes basic network metadata such as your IP address. MacAnswers itself does not save IP addresses to any database. We use them only temporarily in memory to enforce rate limits (so that one person cannot spam the service). However, our hosting provider — like nearly all web hosts — keeps short-term access logs that include client IP addresses for security and debugging purposes. These logs are managed by the hosting provider and typically rotate out within a few weeks.

### If you sign in to use the Campus Issue Tracker

MacAnswers does not have user profiles or accounts in the traditional sense. There is no profile page, no display name, no avatar, and no public identity tied to you.

However, to make the Campus Issue Tracker work, we need a way to verify that the person trying to delete or modify a report is the same person who created it, and to make sure each person can only upvote an issue once. To do this, we use a sign-in step powered by Supabase Authentication. When you sign in, the following minimal record is stored:

- Your McMaster email address
- An internal unique identifier (a random string) generated by Supabase
- Timestamps for when you signed up and last signed in

This record exists only to verify ownership of issues and upvotes. It is not used to build a profile of you, and it is not shown to other users.

If you report a campus issue, we also store:

- The title, description, and category of the issue
- The approximate location (latitude and longitude) you marked on the map
- The building name (if provided)
- The time the issue was reported
- A link between the report and your internal identifier

If you upvote an issue, we store a record linking your internal identifier to that upvote.

We do **not** collect your name, McMaster student number, profile picture, or anything else from your McMaster account beyond your email address.

## Where your data goes

We use a small number of third-party services to operate MacAnswers. Each one only receives the minimum data needed to do its job.

- **Supabase** (database and authentication): stores your sign-in record and any issues you report or upvote. Supabase processes data in accordance with their own privacy policy.
- **Google Gemini API** (embeddings): when you ask a question, the text of your question is sent to Google to generate a numerical representation used for searching the knowledge base. No personal information is sent.
- **Groq** (language model): when you ask a question, the question text plus relevant excerpts from McMaster pages are sent to Groq to generate the answer. No personal information is sent.
- **GitHub** (code and automated scraping): the code for MacAnswers is hosted on GitHub, and we use GitHub Actions to periodically scrape public McMaster web pages. No user data is sent to GitHub.

We do not sell your data, share it with advertisers, or use it for any purpose other than operating MacAnswers.

## Cookies and tracking

MacAnswers uses a single piece of locally-stored data in your browser (a session identifier) to help with rate limiting. This is not a tracking cookie, is not shared with anyone, and is cleared automatically when you close the tab.

We do not use analytics tools, advertising trackers, or any third-party scripts that would profile your activity.

## Public information

Campus issues you report are visible to everyone who uses MacAnswers — that's the point of the feature. The title, description, category, location, and upvote count of each open issue are shown on a public map. Your email address and internal identifier are **not** shown publicly.

If an issue is marked resolved, it is removed from the public map.

## Your choices

### Deleting your own issue reports

You can delete any issue you reported at any time using the delete button on your report. The report is removed permanently.

### Removing your sign-in record

If you want your MacAnswers sign-in record deleted entirely, email **razao2@mcmaster.ca** from the McMaster address you used to sign in. We will remove the authentication record and your upvotes from our system.

Any issue reports you submitted will, by default, remain on the public map but will no longer be linked to you — the community still benefits from the report, but it is no longer associated with your identity. If you would like your reports removed as well, please mention this in your email.

Removal requests are typically completed within seven days.

### Asking what we have on you

You can email **razao2@mcmaster.ca** at any time to ask what information is stored about you. We will respond within a reasonable timeframe.

## Data retention

- **Questions:** not stored. (If this changes, we will update this policy.)
- **Sign-in records and upvotes:** kept until you ask us to remove them.
- **Issue reports:** kept on the public map until resolved by the reporter or removed on request.
- **Hosting provider access logs:** managed by our hosting provider per their own retention schedule, typically a few weeks.

## Security

We follow standard practices to keep data safe, including database-level access controls (Supabase Row Level Security), HTTPS for all traffic, and storing API keys server-side. No system is perfectly secure, but we take reasonable steps to protect what we collect.

If we ever discover a data breach that affects your information, we will notify affected users by email and post a notice on the site.

## Who can use MacAnswers

MacAnswers is intended for current and prospective McMaster University students, staff, and faculty. There is no minimum age requirement for using the search feature, since no personal information is collected. The Campus Issue Tracker is restricted to users with McMaster email addresses, which generally means people who are 16 or older.

If you are under the age of 13, please do not sign in to MacAnswers.

## Changes to this policy

If we change this policy in a material way (for example, beginning to log questions), we will update the "Last updated" date at the top of this page and post a notice on the home page for at least 14 days before the changes take effect. For minor wording changes that don't affect what data we collect or how it's used, we may update silently.

## Jurisdiction

MacAnswers is operated by a student in Ontario, Canada, and is subject to Canadian privacy law, including the *Personal Information Protection and Electronic Documents Act* (PIPEDA). By using MacAnswers, you consent to your data being processed in Canada and in the jurisdictions where our service providers (Supabase, Google, Groq) operate, which may include the United States.

If you have a privacy concern that we have not resolved to your satisfaction, you have the right to contact the Office of the Privacy Commissioner of Canada.

## Disclaimer

MacAnswers provides information drawn from public McMaster pages. We do our best to keep this information accurate and up to date, but we cannot guarantee it. Always verify critical information — financial deadlines, course requirements, exam schedules, safety alerts, anything you would make an important decision based on — directly with McMaster University.

## Contact

For any privacy-related question, request, or concern:

**Email:** razao2@mcmaster.ca

This is the developer's personal McMaster email address. Please use "MacAnswers Privacy" in the subject line so messages don't get lost.
`;

export default function Privacy() {
  return (
    <div className={styles.page}>
      <div className={styles.container}>
        <ReactMarkdown>{POLICY}</ReactMarkdown>
      </div>
    </div>
  );
}
